export const angularQA = [
  // BEGINNER (20)
  { level: 'basic', q: 'What is an Angular module (NgModule)?', a: 'An NgModule is a construct that gathers together components, directives, pipes, and services into cohesive blocks of functionality. Note: In modern Angular (v14+), Standalone Components reduce the need for NgModules.' },
  { level: 'basic', q: 'Why did Angular shift to Standalone Components?', a: 'To reduce boilerplate, simplify the learning curve, and make lazy-loading and tree-shaking more efficient by removing the NgModule abstraction layer.' },
  { level: 'basic', q: 'What is a decorator in Angular?', a: 'A decorator is a function that adds metadata to a class, its members, or its method arguments. Examples: @Component(), @Injectable(), @Input().' },
  { level: 'basic', q: 'What are the main building blocks of Angular?', a: 'Components, Templates, Directives, Pipes, Routing, and Services/Dependency Injection.' },
  { level: 'basic', q: 'What is string interpolation?', a: 'A way to bind a component property to a template, using double curly braces: `{{ propertyName }}`.' },
  { level: 'basic', q: 'What is property binding?', a: 'Binding a component property to a DOM property using square brackets: `[hidden]="isHidden"`.' },
  { level: 'basic', q: 'What is event binding?', a: 'Listening to DOM events and executing a component method using parentheses: `(click)="save()"`.' },
  { level: 'basic', q: 'What is two-way data binding?', a: 'A combination of property and event binding that syncs data between the component and the view. Uses the banana-in-a-box syntax: `[(ngModel)]="name"`.' },
  { level: 'basic', q: 'What is the purpose of the AppRoot component?', a: 'Usually `<app-root>`, it is the top-level component that bootstraps the application and holds the router outlet.' },
  { level: 'basic', q: 'What is angular.json?', a: 'The CLI configuration file containing workspace and project-specific settings for building, serving, test, and linting.' },
  { level: 'basic', q: 'What is the package.json file?', a: 'An npm/node standard file that defines script commands and lists the libraries (dependencies) that the project needs to run.' },
  { level: 'basic', q: 'What is a pipe in Angular?', a: 'A function that takes in data as input and transforms it to a desired output format in the template. Example: `{{ date | date:"shortDate" }}`.' },
  { level: 'basic', q: 'What is ng-template?', a: 'An Angular element for rendering HTML. It is never displayed directly. It is typically used with structural directives (like *ngIf or *ngFor) which instantiate it.' },
  { level: 'basic', q: 'What is ng-container?', a: 'A logical container that does not render an extra element in the DOM. Extremely useful when you need to apply a structural directive (*ngIf) without wrapping the content in a <div>.' },
  { level: 'basic', q: 'How do you structure an Angular project?', a: 'Typically using a feature-based structure: Core folder (singletons), Shared folder (dumb components/pipes), and Feature folders (smart components and routing).' },
  { level: 'basic', q: 'What is the Angular CLI?', a: 'A command-line interface tool to initialize, develop, scaffold, and maintain Angular applications.' },
  { level: 'basic', q: 'How do you create a component using the CLI?', a: '`ng generate component my-comp` or `ng g c my-comp`.' },
  { level: 'basic', q: 'What is an environment file?', a: 'Used to store configuration variables targeting specific environments (like dev, staging, prod), swapped automatically during the build process.' },
  { level: 'basic', q: 'What is the ngOnInit lifecycle hook?', a: 'A lifecycle hook that runs once after the first ngOnChanges. It is the best place to initialize data and make the first API calls.' },
  { level: 'basic', q: 'What is the ngOnDestroy hook?', a: 'Runs right before the component is destroyed. This is critical for cleaning up things like RxJS subscriptions to prevent memory leaks.' },

  // NGRX & STATE MANAGEMENT (15)
  { level: 'advanced', q: 'What is NgRx?', a: 'A reactive State Management library for Angular inspired by Redux, utilizing RxJS heavily.' },
  { level: 'advanced', q: 'What is an NgRx Store?', a: 'A single, immutable data structure that represents the state of your entire application.' },
  { level: 'advanced', q: 'What is an NgRx Action?', a: 'An object describing an event that has happened in the application, dispatched to the store. Created via `createAction`.' },
  { level: 'advanced', q: 'What is an NgRx Reducer?', a: 'A pure function that takes the current state and a dispatched Action, and returns a new updated state object.' },
  { level: 'advanced', q: 'What is an NgRx Selector?', a: 'Pure functions used for obtaining slices of store state. They memorize (cache) previous results for performance.' },
  { level: 'advanced', q: 'What are NgRx Effects?', a: 'A side effect model. They listen for actions dispatched from the store, perform operations (like API calls), and then dispatch new actions.' },
  { level: 'advanced', q: 'What is the NgRx Entity pattern?', a: 'A utility to manage collections of entities (lists of objects). It provides an adapter with CRUD operations and normalizes data into an `{ ids: [], entities: {} }` structure for rapid lookups.' },
  { level: 'advanced', q: 'What is NgRx SignalStore?', a: 'A lightweight, fully functional state management solution built on Angular Signals. It requires no Actions or Reducers boilerplate and is the modern approach for local or global state in v17+.' },
  { level: 'intermediate', q: 'When should you use Global State vs Local State?', a: 'Use Global (NgRx Store) for data shared across multiple distant components, user sessions, or cached API results. Use Local (ComponentStore/SignalStore) for data specific to a feature module or complex component.' },
  { level: 'advanced', q: 'How do you handle loading/error states in NgRx?', a: 'Typically by defining three distinct actions: `loadEntities`, `loadEntitiesSuccess`, and `loadEntitiesFailure`. The reducer updates `isLoading` and `error` flags accordingly.' },
  { level: 'intermediate', q: 'What is the facade pattern in Angular component state?', a: 'A service that injects the Store and provides selected Observables/Signals and methods to dispatch actions. This hides NgRx complexity from the "dumb" UI components.' },
  { level: 'advanced', q: 'How does time-travel debugging work in Redux/NgRx?', a: 'Since the store state is immutable, every action creates a new snapshot. The Redux DevTools extension allows you to rewind and jump between these immutable state snapshots.' },
  { level: 'advanced', q: 'What happens if a reducer is not a pure function?', a: 'The state could mutate in place, leading to unpredictable bugs and preventing Angular from knowing if the state reference changed (breaking OnPush change detection).' },
  { level: 'advanced', q: 'What is the difference between switchMap and concatMap inside NgRx Effects?', a: '`switchMap` cancels the previous inner observable if a new action arrives (good for GET requests/search). `concatMap` queues the inner observables in order (good for POST/PUT requests where order matters).' },
  { level: 'expert', q: 'How do you test NgRx code?', a: 'Reducers and Selectors are tested as pure functions. Effects are tested using `provideMockActions` and jasmine marbles (hot/cold observables). Components are tested by mocking the Store via `provideMockStore`.' },

  // TESTING (15)
  { level: 'intermediate', q: 'What is the Angular TestBed?', a: 'A powerful unit testing utility that configures and initializes the environment for writing unit tests, creating a dynamic module for the component context.' },
  { level: 'intermediate', q: 'What is describe, beforeAll, beforeEach, it in Jasmine?', a: '`describe` groups tests. `it` defines a specific test. `beforeEach` runs setup code before EVERY test in the block. `beforeAll` runs setup code ONCE for the block.' },
  { level: 'advanced', q: 'What is MockComponent and why use it?', a: 'A dummy version of a child component used to isolate the parent component being tested. It prevents the test from failing due to child dependencies.' },
  { level: 'advanced', q: 'How do you test services with HTTP dependencies?', a: 'By injecting the `HttpTestingController` (via `provideHttpClientTesting()`). You can expect requests, flush them with mock data, and verify no outstanding requests remain.' },
  { level: 'advanced', q: 'What are Component Harnesses?', a: 'A concept from Angular CDK testing. It provides a robust API for interacting with components (like MatSelect) without relying on fragile CSS DOM selectors.' },
  { level: 'intermediate', q: 'What is a Spy in Jasmine/Jest?', a: 'A mocked function that tracks information about if and how it was called (arguments, call count) and allows you to fake its return value (`spyOn(obj, "method").and.returnValue()`).' },
  { level: 'advanced', q: 'How do you test a component with OnPush change detection?', a: 'Since `fixture.detectChanges()` might not work if inputs haven\'t changed, you often have to simulate the event or call `fixture.componentRef.setInput()` in newer Angular versions.' },
  { level: 'intermediate', q: 'What is the difference between fixture.debugElement and fixture.nativeElement?', a: '`nativeElement` provides the raw DOM element. `debugElement` is an Angular wrapper that provides access to the component instance, directives, and custom query predicates (`By.css`).' },
  { level: 'advanced', q: 'How do you test Angular Signals?', a: 'Since signals are synchronous and pull-based, you simply set the signal (`mySignal.set(val)`) and assert the computed value or template output immediately after `detectChanges()`.' },
  { level: 'advanced', q: 'What is the fakeAsync zone?', a: 'It allows you to test asynchronous code (like `setTimeout` or Promises) in a synchronous way, by letting you manually advance time using `tick(ms)` or `flush()`, avoiding flaky asynchronous tests.' },
  { level: 'advanced', q: 'What is the difference between tick() and flush()?', a: '`tick(ms)` advances the virtual clock by a specific amount of time. `flush()` advances time until the macrotask queue is completely empty.' },
  { level: 'intermediate', q: 'How do you test an Angular Route Guard?', a: 'Extract the functional guard or class injectables into the test file, provide any required mock services (like AuthService), call the guard function directly, and check if it returns true, false, or a UrlTree.' },
  { level: 'intermediate', q: 'Why is NO_ERRORS_SCHEMA considered an anti-pattern?', a: 'It tells the compiler to ignore unrecognized elements and attributes. While it suppresses errors for missing child components, it also masks genuine typos (e.g., `<app-utten>` instead of `<app-button>`).' },
  { level: 'advanced', q: 'How do you test un-exported functions or private component states?', a: 'You shouldn\'t. Tests should verify the public API and observable side effects (DOM output, service calls) rather than brittle internal implementation details.' },
  { level: 'expert', q: 'How do you mock the router in tests?', a: 'Use `provideRouter([])` with an empty config, or inject a mock object for `Router` via `provide({provide: Router, useValue: mockRouter})` and spy on its `navigate` or `navigateByUrl` methods.' },

  // ADVANCED ARCHITECTURE AND INTERNALS (30)
  { level: 'expert', q: 'What is the Angular Compiler (Ivy)?', a: 'Ivy is the rendering engine in modern Angular. It compiles components into highly efficient DOM instructions at build time, significantly reducing bundle size.' },
  { level: 'expert', q: 'What are tree-shakable providers (`providedIn: root`)?', a: 'By providing a service in `root`, Angular does not need it registered in any module. If the service is never injected anywhere, the bundler can safely drop its code from the final payload.' },
  { level: 'expert', q: 'Explain Zone.js and its role in Angular.', a: 'Zone.js monkeys-patches standard async browser APIs (setTimeout, XHR, DOM events). When an async task completes, Zone.js tells Angular, which then triggers change detection from top to bottom (unless OnPush).' },
  { level: 'expert', q: 'What does "Zone-less Angular" mean?', a: 'In Angular 18+, with Signals and the `provideExperimentalZonelessChangeDetection()` API, Angular no longer needs Zone.js. It precisely tracks exactly which DOM nodes need updating via tracking signals.' },
  { level: 'expert', q: 'What is hydration vs destratification in SSR?', a: 'Hydration is attaching event listeners and state to server-rendered HTML. Angular 16 introduced Non-Destructive Hydration, which no longer destroys the DOM before recreating it.' },
  { level: 'advanced', q: 'What is control flow migration in Angular 17?', a: 'Moving from structural directives (`*ngIf`, `*ngFor`) to built-in template syntax (`@if`, `@for`). It compiles much faster, performs better, and requires no module imports.' },
  { level: 'advanced', q: 'What is Deferrable Views (`@defer`)?', a: 'A declarative way to lazy-load components directly in the template. `@defer (on viewport) { <heavy-chart /> }` will chunk the chart component and only load it when it scrolls into view.' },
  { level: 'advanced', q: 'What are esbuild and Vite doing in Angular 17+?', a: 'Webpack was replaced. Esbuild compiles JS/TS blazingly fast. Vite serves the local dev server using native ES modules for immediate updates without rebundling the whole app.' },
  { level: 'expert', q: 'What is a forwardRef and when do you need it?', a: 'A function that allows referencing a class before it has been fully defined. It\'s required when a class injects a service that is declared later in the file, or when a component implements `ControlValueAccessor` and provides itself.' },
  { level: 'expert', q: 'What is the Angular Injector hierarchy?', a: 'Angular has two injector trees: The ModuleInjector hierarchy (`@Injectable({providedIn: root/module})`) and the ElementInjector hierarchy (providers on the `@Component()` or `@Directive()`). Resolution starts at the Element and falls back to the Module.' },
  { level: 'advanced', q: 'Describe how `HostListener` and `HostBinding` work.', a: '`@HostListener` binds to an event on the host element of the component/directive. `@HostBinding` binds a property of the class to an attribute/class/style of the host element.' },
  { level: 'expert', q: 'What is Dependency Injection Token (InjectionToken)?', a: 'A token used to inject non-class dependencies like string configs, interfaces, or plain objects into constructors because interfaces disappear at runtime in TypeScript.' },
  { level: 'advanced', q: 'How does Angular handle XSS attacks?', a: 'Angular considers all values untrusted and automatically sanitizes values depending on the context: HTML (escapes script tags), Style (blocks dangerous CSS), and URLs (prevents javascript: URIs).' },
  { level: 'advanced', q: 'How do you bypass Angular sanitization?', a: 'By injecting the `DomSanitizer` service and calling `bypassSecurityTrustHtml()`, `bypassSecurityTrustUrl()`, or `bypassSecurityTrustResourceUrl()`. Use sparingly!' },
  { level: 'advanced', q: 'What is the difference between ViewChild and ContentChild?', a: '`@ViewChild` accesses elements/components defined in the component\'s OWN template. `@ContentChild` accesses elements projected from the PARENT component via `<ng-content>`.' },
  { level: 'advanced', q: 'What is `static: true` in ViewChild?', a: 'If `true`, Angular resolves the query BEFORE change detection runs, meaning the element must not be inside an `*ngIf`. Useful when injecting the element in `ngOnInit`.' },
  { level: 'expert', q: 'How does Dependency Injection resolution work with `Host`, `Self`, `SkipSelf`, and `Optional` decorators?', a: '`@Optional`: Returns null if not found. `@Self`: Looks ONLY on the current component. `@SkipSelf`: Starts looking from the parent component. `@Host`: Stops looking when it reaches the host component (the boundary of the custom element).' },
  { level: 'advanced', q: 'What is a Router Outlet?', a: 'A directive (`<router-outlet>`) that acts as a placeholder where the router should display the components corresponding to the active route.' },
  { level: 'expert', q: 'What are intercepting routes?', a: 'Not native Angular terminology (that\'s Next.js). In Angular, we intercept HTTP requests via `HttpInterceptorFn`. It modifies outgoing requests (e.g., adding Auth tokens) or incoming responses (handling global errors).' },
  { level: 'advanced', q: 'What is a Resolver in routing?', a: 'A function that pre-fetches data before the route transition completes. The route will wait for the resolver observable to emit to prevent a blank UI.' },
  { level: 'advanced', q: 'What is an Entry Component?', a: 'A component loaded imperatively by code (like a Modal or Dialog) rather than declared in a template. In Ivy (v9+), you no longer need to declare them in `entryComponents` arrays.' },
  { level: 'advanced', q: 'What is APP_INITIALIZER?', a: 'An InjectionToken allowing you to run a function or Promise BEFORE the Angular app finishes bootstrapping. Great for loading initial config files.' },
  { level: 'expert', q: 'Explain ChangeDetectionStrategy.OnPush.', a: 'Tells Angular to only check the component when its `@Input()` references change, an event originates from within the component, an async pipe emits, or the new Signal state changes. Vastly improves performance.' },
  { level: 'advanced', q: 'What is a TrackBy function?', a: 'Used with `*ngFor` (or the `track` block in `@for`). It tells Angular how to uniquely identify items. If the array reference changes, Angular only updates DOM nodes that actually changed instead of destroying and recreating the whole list.' },
  { level: 'expert', q: 'How do you create a custom form control?', a: 'By implementing the `ControlValueAccessor` interface (`writeValue`, `registerOnChange`, `registerOnTouched`, `setDisabledState`) and providing it via the `NG_VALUE_ACCESSOR` token.' },
  { level: 'advanced', q: 'What is the ViewEncapsulation property?', a: 'It determines how styles are scoped to the component. `Emulated` (default) adds unique attributes to isolate styles. `None` applies them globally. `ShadowDom` uses native Shadow DOM.' },
  { level: 'expert', q: 'What is the purpose of `markForCheck()` vs `detectChanges()`?', a: '`markForCheck()` flags the component and all its ancestors to be checked in the NEXT normal change detection run. `detectChanges()` forces an immediate, synchronous check of the component and its children.' },
  { level: 'expert', q: 'What is `ngDoCheck`?', a: 'A lifecycle hook that triggers on EVERY change detection cycle, regardless of whether inputs changed. Highly dangerous to use because it executes very frequently; only use it for tracking complex internal object mutations if absolutely necessary.' },
  { level: 'advanced', q: 'How do you dynamically load a component at runtime?', a: 'Using `ViewContainerRef.createComponent()`, passing the imported component class. It allows injecting the component into a specific #placeholder in the DOM.' },
  { level: 'expert', q: 'What is `effect()` in Angular Signals?', a: 'An operation that runs when one or more signals it reads change. Useful for bridging signals to non-signal code (like DOM APIs, logging, or setting up RxJS subjects).' },

  // --- NEW ADDITIONS (80+ ITEMS) ---
  // BEGINNER GAPS
  { level: 'basic', q: 'What is the difference between a Component and a Directive?', a: 'A Component is a Directive with a template. It is the building block of the UI, while a Directive (Attribute/Structural) adds behavior/appearance to an existing element.' },
  { level: 'basic', q: 'What is TypeScript and why does Angular use it?', a: 'TypeScript is a typed superset of JavaScript. Angular uses it for early error detection, better IDE tooling (intellisense), and to handle decorators and interfaces effectively.' },
  { level: 'basic', q: 'What is the purpose of the `selector` in @Component?', a: 'It defines the CSS selector that identifies this component in a template (e.g., `<app-nav>`).' },
  { level: 'basic', q: 'What is the `providers` array in a component for?', a: 'It allows registering services at the component level (ElementInjector), creating a separate instance of the service for that component and its children.' },
  { level: 'basic', q: 'What is the difference between `const` and `let` in TypeScript?', a: '`const` is for values that won\'t be reassigned. `let` is for block-scoped variables that can be reassigned.' },
  { level: 'basic', q: 'What is an Interface?', a: 'A syntax for defining the structure of an object without implementing it. It exists only at compile-time for type checking.' },
  { level: 'basic', q: 'What is the `constructor` used for in Angular components?', a: 'Primarily for Dependency Injection. Heavy initialization logic should be moved to `ngOnInit`.' },
  { level: 'basic', q: 'How do you handle user input in it template?', a: 'Using event binding, e.g., `(input)="onInput($event)"`.' },
  { level: 'basic', q: 'What is the `ngFor` trackBy function?', a: 'A function that returns a unique identifier for list items, preventing the entire list from re-rendering if only middle items change.' },
  { level: 'basic', q: 'What is the purpose of `target` in tsconfig.json?', a: 'Specifies the ECMAScript version (e.g., ES2022) that the TypeScript compiler will output.' },

  // NGRX & STATE MANAGEMENT (ADDITIONAL)
  { level: 'advanced', q: 'What is "Prop Drilling" and how does NgRx solve it?', a: 'Passing data through multiple levels of components just to reach a child. NgRx allows components to "select" data directly from the store, bypassing intermediate parents.' },
  { level: 'expert', q: 'What is `patchState` in NgRx SignalStore?', a: 'A function that allows updating the state of a SignalStore in a type-safe way, merging the partial state into the current one.' },
  { level: 'advanced', q: 'How do you handle optimistic updates in NgRx?', a: 'Update the store immediately when an action is dispatched, and if the subsequent API call fails, dispatch a "Failure" action to revert (rollback) the state.' },
  { level: 'expert', q: 'Compare ComponentStore vs Store vs SignalStore.', a: '`Store` is for global, complex cross-feature state. `ComponentStore` is for complex local state using RxJS. `SignalStore` is the unified modern approach for both, utilizing Signals for performance.' },
  { level: 'advanced', q: 'What is a "Container" vs "Presentational" component pattern?', a: 'Containers (Smart) know about state/services. Presentational (Dumb) receive data via @Input and emit via @Output, making them highly reusable and testable.' },
  { level: 'expert', q: 'How do you prevent circular dependencies in NgRx?', a: 'By isolating Actions and Selectors into separate files and using "barrel" imports carefully, or by using "Feature State" slices.' },
  { level: 'advanced', q: 'What is NGRX Router Store?', a: 'A library that syncs the Angular Router state with the NgRx store, allowing you to use route parameters in your selectors.' },
  { level: 'expert', q: 'What is state normalization and why do it?', a: 'Storing data as flat objects indexed by IDs (like a database) instead of nested trees. It prevents data duplication and makes updates extremely fast via NgRx Entity.' },

  // TESTING (ADDITIONAL)
  { level: 'advanced', q: 'What are "Jasmine Marbles"?', a: 'A testing syntax for RxJS observables using visual representations (`-`, `a`, `|`, `#`) to assert timing and values of hot/cold observables.' },
  { level: 'advanced', q: 'Why is `fixture.whenStable()` used?', a: 'It returns a promise that resolves when all pending asynchronous activities in the Angular Zone have completed.' },
  { level: 'expert', q: 'How do you test a component that uses `@defer`?', a: 'By using the `ComponentFixture.getComponentDeferInstances()` API to manually trigger the different states (prefetch, loading, error, complete) of the deferred block.' },
  { level: 'advanced', q: 'What is the difference between `spyOn` and `jasmine.createSpyObj`?', a: '`spyOn` mocks an existing method on a real object. `createSpyObj` generates a completely new mock object with specified methods.' },
  { level: 'advanced', q: 'How do you mock the `HttpClient`?', a: 'Using `HttpClientTestingModule` and `HttpTestingController` to intercept and flush requests.' },
  { level: 'expert', q: 'Explain visual regression testing in Angular.', a: 'Taking screenshots of components/pages and comparing them pixel-by-pixel against reference images to detect UI changes (e.g., using Playwright or Applitools).' },
  { level: 'intermediate', q: 'What is "Integration Testing" in the context of Angular?', a: 'Testing a component and its real child components together, rather than mocking all children (Shallow testing).' },

  // ANIMATIONS
  { level: 'intermediate', q: 'What is the `trigger()` function in Angular animations?', a: 'It defines the name of the animation and the collection of states and transitions associated with it.' },
  { level: 'advanced', q: 'What is the `*` and `void` state in animations?', a: '`void` is the state when an element is not in the DOM. `*` is a wildcard represents any state. Transition `void => *` happens when an element enters.' },
  { level: 'advanced', q: 'How do you create staggered animations?', a: 'Using the `stagger()` function within a `query()` to introduce a delay between multiple elements animating in a sequence.' },
  { level: 'intermediate', q: 'Can you use CSS variables in Angular animations?', a: 'Yes, they can be accessed via `style({ transform: "var(--my-var)" })` within transitions.' },
  { level: 'expert', q: 'How do you disable animations globally for tests?', a: 'By providing `NoopAnimationsModule` instead of `BrowserAnimationsModule` in the test setup.' },

  // i18n & L10N
  { level: 'intermediate', q: 'What is the `i18n` attribute in templates?', a: 'A built-in attribute used to mark static text for translation. The Angular CLI extracts these into XLIFF files.' },
  { level: 'advanced', q: 'What are ICU expressions in Angular i18n?', a: 'Syntax used to handle pluralization (`plural`) and selection (`select`) based on variable values within a translation.' },
  { level: 'expert', q: 'How do you swap languages at runtime?', a: 'Angular\'s built-in i18n is compile-time. For runtime translation, libraries like `@ngx-translate` or modern `@angular/localize` runtime strategies are used.' },

  // PWA & SERVICE WORKERS
  { level: 'intermediate', q: 'What is a Manifest file in a PWA?', a: 'A JSON file (`manifest.webmanifest`) that tells the browser how the app should behave when installed (icons, theme color, splash screen).' },
  { level: 'advanced', q: 'How does `@angular/service-worker` handle updates?', a: 'It checks for a new `ngsw.json` file. If a new version is found, it downloads all assets in the background and prompts the user via `SwUpdate` service.' },
  { level: 'advanced', q: 'What is "Safety Worker" in Angular PWA?', a: 'A tiny fallback service worker used to unregister old, problematic workers if a corruption is detected.' },

  // MICRO-FRONTENDS
  { level: 'expert', q: 'What is Module Federation?', a: 'A Webpack/Esbuild feature that allows a host application to dynamically load compiled modules from a remote application at runtime.' },
  { level: 'expert', q: 'What are Angular Elements?', a: 'Angular components packaged as custom elements (Web Components), allowing them to be used in any HTML environment (React, Vue, plain HTML).' },

  // SECURITY & BUILD
  { level: 'advanced', q: 'What is Content Security Policy (CSP)?', a: 'A security header that tells the browser which sources of scripts, styles, and images are trusted, preventing XSS attacks.' },
  { level: 'expert', q: 'What is the difference between JIT and AOT compilation?', a: 'JIT (Just-In-Time) compiles in the browser at runtime. AOT (Ahead-Of-Time) compiles during the build process. AOT is default and much faster/secure.' },
  { level: 'advanced', q: 'What is "PurgeCSS" for Angular?', a: 'A tool that analyzes templates at build time to remove unused global CSS, reducing bundle size (often used with Tailwind).' },
  { level: 'expert', q: 'What is "Differential Loading"?', a: 'Generating two sets of bundles: ES2015+ for modern browsers and ES5 for legacy ones, ensuring everyone gets the smallest possible code.' },

  // ACCESSIBILITY (A11Y)
  { level: 'intermediate', q: 'What is the `cdk/a11y` FocusTrap?', a: 'A utility that traps keyboard focus within a specific element (like a Dialog), preventing the user from tabbing out of it.' },
  { level: 'advanced', q: 'How do you handle Live Regions in Angular?', a: 'By using the `LiveAnnouncer` service from Angular CDK to announce dynamic changes (like errors or success messages) to screen readers.' },
  { level: 'intermediate', q: 'What is the purpose of ARIA labels?', a: 'Accessible Rich Internet Applications labels provide descriptive text for elements that don\'t have a visible label (like icon-only buttons) for screen readers.' },

  // MISC / v22+
  { level: 'expert', q: 'What is "Selectorless Components"?', a: 'Proposed features where components don\'t require a tag name and can be instantiated strictly via code or routes.' },
  { level: 'advanced', q: 'What is the `linkedSignal()`?', a: 'A signal whose value is derived from another signal but can also be manually updated (writable computed signal).' },
  { level: 'expert', q: 'What is "Partial Hydration" in Angular SSR?', a: 'A technique where only specific interactive parts of the page are hydrated, while static parts remain pure HTML to save JS execution time.' },
  { level: 'advanced', q: 'What is the `output()` function in v18+?', a: 'A signal-safe replacement for the `@Output()` decorator, using the new `output()` API for cleaner event emission.' },
  { level: 'basic', q: 'What is the difference between `npm install` and `npm ci`?', a: '`install` can update the lockfile. `ci` (Clean Install) is for automated environments; it requires a lockfile and deletes `node_modules` before fresh install.' },
  { level: 'intermediate', q: 'What is an "Injection Context"?', a: 'A period during execution where `inject()` can be used (e.g., in a constructor or a factory function).' },
  { level: 'advanced', q: 'How do you optimize an Angular app for the "First Contentful Paint" (FCP)?', a: 'Using SSR, critical CSS inlining, image lazy-loading, and route-based code splitting.' },
  { level: 'advanced', q: 'What is "Hydration Mismatch"?', a: 'An error when the server-rendered HTML doesn\'t match the client-side initial state, causing Angular to destroy and recreate the DOM.' },
  { level: 'expert', q: 'How do you implement a "Micro-Frontend" using Native Federation?', a: 'By using the `@angular-architects/native-federation` package, which uses standard browser import maps instead of Webpack-specific logic.' },
  { level: 'intermediate', q: 'What is the purpose of `ngSrc` directive?', a: 'A directive for optimized image loading that automatically handles lazy loading, priority, and responsive sizing.' }
];
