export const sysDesignQA = [
  // SYSTEM DESIGN BEGINNER (10)
  { level: 'basic', q: 'What is System Design?', a: 'The process of defining the architecture, modules, interfaces, and data for a system to satisfy specified requirements. It\'s about making high-level architectural choices to scale.' },
  { level: 'basic', q: 'What is a Load Balancer?', a: 'A device or software (like Nginx or HAProxy) that acts as a reverse proxy and distributes network or application traffic across a number of servers to prevent single-point overload.' },
  { level: 'basic', q: 'Explain Horizontal vs Vertical Scaling.', a: 'Vertical scaling (Scaling Up) means upgrading a single server\'s hardware. Horizontal scaling (Scaling Out) means adding more independent servers to a pool to share the load.' },
  { level: 'basic', q: 'What is a CDN (Content Delivery Network)?', a: 'A geographically distributed network of proxy servers and their data centers. The goal is to cache static assets (like images, JS, CSS) closer to users to reduce latency drastically.' },
  { level: 'basic', q: 'What is database caching?', a: 'Storing frequently accessed data in a fast, in-memory store (like Redis or Memcached) to reduce the number of slow, heavy queries hitting the primary database.' },
  { level: 'basic', q: 'What does stateful vs stateless mean?', a: 'A stateless architecture means the server does not store any information about the client session (every request must contain all auth info, like JWTs). Stateful means the server remembers the client (like saving a session ID in memory).' },
  { level: 'basic', q: 'What is the purpose of a Reverse Proxy?', a: 'A server that sits in front of web servers and forwards client requests to them. Used for load balancing, SSL termination, and caching.' },
  { level: 'basic', q: 'Explain basically what a Microservice architecture is.', a: 'Breaking down a massive monolithic application into small, independent, specialized services that communicate over APIs. Each service can be developed, deployed, and scaled totally independently.' },
  { level: 'basic', q: 'What is DNS?', a: 'Domain Name System. The phonebook of the internet. It translates human-readable domain names (google.com) into computer-readable IP addresses.' },
  { level: 'basic', q: 'What is API Rate Limiting?', a: 'Restricting the number of requests a user or IP can make to an API within a specific time window to prevent abuse, scraping, or DDoS attacks.' },

  // SYSTEM DESIGN INTERMEDIATE / ADVANCED (10)
  { level: 'intermediate', q: 'Explain the CAP Theorem.', a: 'In a distributed data store, you can only mathematically guarantee two of three traits: Consistency (every read gets the latest write), Availability (every request gets a response), and Partition Tolerance (system works despite network drops). Because of network physics, you must choose CP or AP.' },
  { level: 'advanced', q: 'What is Database Sharding?', a: 'Horizontally partitioning a database. Instead of one massive DB, you split data across multiple databases using a shard key (e.g., users A-M on DB1, N-Z on DB2). It solves pure dataset size limits but makes cross-shard joins impossible.' },
  { level: 'intermediate', q: 'What is the "Thundering Herd" problem in caching?', a: 'When a popular cache key expires, thousands of concurrent requests miss the cache simultaneously and instantly slam the primary database, often crashing it. Solution: Use cache locks or add slight random jitter to expiration times.' },
  { level: 'advanced', q: 'Explain Eventual Consistency vs Strong Consistency.', a: 'Strong consistency guarantees that once a write occurs, all subsequent reads instantly reflect it (slow). Eventual consistency allows temporary staleness across replicated nodes, but guarantees they will ultimately synchronize (fast).' },
  { level: 'advanced', q: 'What is Long Polling vs WebSockets vs Server-Sent Events?', a: 'Long polling holds an HTTP connection open until the server has new data. WebSockets provide a true full-duplex, persistent TCP connection for two-way realtime data. Server-Sent Events (SSE) provide a persistent one-way connection from server to client.' },
  { level: 'expert', q: 'Explain Consistent Hashing and why it is used.', a: 'A hashing technique used in distributed systems (like Memcached clusters). Instead of modulo hashing which requires massive data reshuffling if a node is added/removed, consistent hashing places nodes on a circular hash ring, meaning adding/removing a node only disrupts its immediate neighbor.' },
  { level: 'advanced', q: 'What is a Message Queue?', a: 'An asynchronous service-to-service communication mechanism (like RabbitMQ or Kafka) used to decouple heavy processing. App servers push tasks onto the queue instantly, while worker servers pull tasks off the queue at their own pace without crashing.' },
  { level: 'intermediate', q: 'What is the difference between SQL and NoSQL?', a: 'SQL offers strict schemas, complex joins, and ACID compliance (scale vertically). NoSQL offers flexible schemas, sacrifices strong consistency for massive horizontal scalability, and is optimized for specific access patterns like key-value or document storage.' },
  { level: 'expert', q: 'What is the Two-Phase Commit (2PC) protocol?', a: 'A distributed algorithm that coordinates all processes participating in a distributed atomic transaction on whether to commit or abort (rollback) the transaction. It ensures ACID properties across multiple disparate databases.' },
  { level: 'expert', q: 'How would you design a URL shortener like bit.ly?', a: 'Requirements: High read-to-write ratio. Tech: Relational DB for strict ACID, or NoSQL for sheer scale. Algorithm: Base62 encoding of a unique auto-incrementing integer ID. Use Memcached heavily to cache the `shortURL -> longURL` mapping since reads outnumber writes 100:1.' },
  { level: 'expert', q: 'Explain the difference between L4 and L7 Load Balancing.', a: 'L4 (Transport Layer) balances based on IP and TCP/UDP ports; it is fast but cannot see application data. L7 (Application Layer) balances based on HTTP headers, cookies, and URL paths; it is slower but enables intelligent routing (e.g., sending /api to different servers than /static).' },
  { level: 'expert', q: 'What is a Conflict-free Replicated Data Type (CRDT)?', a: 'A data structure which can be replicated across multiple nodes in a network where replicas can be updated independently and concurrently without coordination, and it is mathematically guaranteed to converge to a consistent state.' },
  { level: 'expert', q: 'Explain the "Saga Pattern" for distributed transactions.', a: 'A failure management pattern that helps establish consistency in distributed systems. It coordinates transactions between multiple microservices using a sequence of local transactions. If one fails, the Saga executes "compensating transactions" to undo the preceding successful transactions.' },
  { level: 'expert', q: 'What is CQRS (Command Query Responsibility Segregation)?', a: 'An architectural pattern that separates the models for reading and writing data. Commands (writes) use one model/database, while Queries (reads) use another (often a flattened/denormalized read replica). This allows independent scaling of read and write workloads.' },
  { level: 'expert', q: 'Explain the concept of "Sidecars" in microservices.', a: 'A deployment pattern where a helper container (the sidecar) is attached to the main application container to handle peripheral tasks like logging, monitoring, or service-mesh networking (e.g., Envoy/Istio) without modifying the app code.' },
  { level: 'expert', q: 'What is the "Thundering Herd" problem and how do you mitigate it?', a: 'When a popular cached item expires, many concurrent requests all trigger a database re-fetch simultaneously. Mitigation: Use "Lease" or "Locking" where only one request updates the cache while others wait or serve slightly stale data.' },
  { level: 'expert', q: 'Compare Optimistic vs Pessimistic Locking.', a: 'Pessimistic locking assumes conflicts will happen and locks the record before update (blocking). Optimistic locking assumes conflicts are rare; it checks a version/timestamp during the update and fails if it has changed, requiring a retry (non-blocking).' },
  { level: 'expert', q: 'What is "Write-Ahead Logging" (WAL)?', a: 'A standard technique for providing atomicity and durability in databases. Changes are first written to a persistent log file before being applied to the actual data files. This allows the DB to recover state after a crash.' },
  { level: 'expert', q: 'Explain "Fan-out" in messaging systems.', a: 'The process of delivering a single message to multiple consumers or queues simultaneously. Commonly used for social media feeds: when a celebrity posts, the message fans out to the feeds of millions of followers.' },
  { level: 'expert', q: 'What are Bloom Filters and why use them in System Design?', a: 'A space-efficient probabilistic data structure used to test whether an element is a member of a set. It can return "false positive" matches but NEVER "false negatives". Use: checking if a username is taken or if a URL is malicious before hitting a slow DB.' },
  { level: 'expert', q: 'What is the "N+1 Query Problem" and how do you solve it?', a: 'Happens when an ORM executes one query to fetch parent records, and then N additional queries to fetch children of each parent. Solution: Use "Eager Loading" (SQL Joins or IN clauses) to fetch all required data in 1 or 2 queries.' },
  { level: 'expert', q: 'Explain "Backpressure" in distributed streams.', a: 'A mechanism that allows a overwhelmed consumer to tell a producer to slow down or stop sending data until the consumer catches up. Essential for stability in systems like Kafka, Akka, or Reactive Streams.' },
  { level: 'expert', q: 'What is a "Circuit Breaker" in microservices?', a: 'A state machine that prevents a service from calling another service that is likely to fail. States: CLOSED (calls allowed), OPEN (calls blocked for N seconds), and HALF-OPEN (allows a few test calls). Stops "cascading failures" throughout the system.' },
  { level: 'expert', q: 'Explain "Shadow DOM" isolation benefits for Design Systems.', a: 'Shadow DOM allows for complete CSS and DOM encapsulation. It ensures that styles defined in a design system component (like a button) cannot be accidentally overridden by "global" styles on the host page, and vice versa.' }
];

export const uxUiQA = [
  // UX/UI BEGINNER (10)
  { level: 'basic', q: 'What is the difference between UX and UI?', a: 'UX (User Experience) is the analytical logic, psychology, and feel of the experience (wireframes, research, user journeys). UI (User Interface) is the visual skin, typography, colors, and layout (the aesthetic presentation).' },
  { level: 'basic', q: 'What is whitespace (negative space)?', a: 'The empty area separating different visual elements. It is crucial for preventing cognitive overload and effectively grouping related items together.' },
  { level: 'basic', q: 'What is progressive disclosure?', a: 'An interaction design technique that defers advanced or rarely used features to a secondary screen/dropdown, making applications easier to learn and less error-prone. (e.g., An "Advanced Settings" toggle).' },
  { level: 'basic', q: 'What is a Call to Action (CTA)?', a: 'A prominent button or link designed to prompt an immediate response or encourage an immediate sale (e.g., "Sign Up Now" or "Buy It").' },
  { level: 'basic', q: 'What is the 60-30-10 color rule?', a: 'A classic design principle for creating a balanced color palette. 60% is your dominant hue (usually background), 30% is your secondary color, and 10% is your accent color (CTAs and highlights).' },
  { level: 'basic', q: 'What are wireframes vs mockups vs prototypes?', a: 'Wireframes are low-fidelity structural blueprints (gray boxes). Mockups are high-fidelity static visual designs (colors and fonts). Prototypes are interactive models simulating the final flow.' },
  { level: 'basic', q: 'Why is Typography important in UI?', a: 'It establishes visual hierarchy, guides eye tracking, heavily impacts readability, and sets the entire emotional tone and brand identity of an application.' },
  { level: 'basic', q: 'What is Affordance in design?', a: 'A physical characteristic of an object or interface that visually hints at how it should be used. For example, a 3D shadow on a button affords clicking. A slider affords dragging.' },
  { level: 'basic', q: 'What is Mobile-First Design?', a: 'Designing the UI and UX for the smallest screen (mobile) first, focusing purely on core features, and progressively enhancing the layout for larger tablet and desktop screens.' },
  { level: 'basic', q: 'What does accessibility mean in UI design?', a: 'Ensuring your design is usable by people with disabilities. This means maintaining high color contrast, ensuring keyboard navigability, and providing screen-reader labels.' },

  // UX/UI INTERMEDIATE/ADVANCED (10)
  { level: 'intermediate', q: 'Explain Fitts\'s Law.', a: 'The time required to move to a target is a function of the distance to the target and the size of the target. Therefore, primary actions should be large and close to the user\'s natural starting position.' },
  { level: 'intermediate', q: 'Explain Hick\'s Law.', a: 'The time it takes to make a decision increases with the number and complexity of choices. In UX, this means you should minimize the number of options (e.g. navigation links) presented at once to prevent paralysis.' },
  { level: 'intermediate', q: 'What is the Gestalt Principle of Proximity?', a: 'Items physically close to each other are perceived as being grouped or related to one another. It is the strongest way to establish relationships without drawing literal bounding boxes.' },
  { level: 'advanced', q: 'What is the Aesthetic-Usability Effect?', a: 'A psychological phenomenon where users perceive more aesthetically pleasing designs to be more intuitive and easier to use than less pleasing designs, even if the actual usability is identical.' },
  { level: 'advanced', q: 'Describe Skeleton Screens vs Spinners.', a: 'Skeleton screens display a blank version of a page into which information is gradually loaded, reducing the user\'s *perceived* wait time. Spinners just show a loading wheel and increase frustration for long loads.' },
  { level: 'advanced', q: 'What are Dark Patterns?', a: 'UI and UX design choices specifically engineered to trick users into doing things they did not intend to do, like sneaking items into a cart or making the "Cancel Subscription" button invisible.' },
  { level: 'expert', q: 'What is Cognitive Load in UX?', a: 'The total amount of mental effort being used in the working memory. Extraneous cognitive load generated by cluttered UI, unclear labels, and disruptive pop-ups severely degrades user success rates.' },
  { level: 'advanced', q: 'Explain Heuristic Evaluation.', a: 'A usability engineering method where evaluators examine the UI and judge its compliance with recognized usability principles (the "heuristics"), such as Nielsen\'s 10 Usability Heuristics.' },
  { level: 'expert', q: 'How do you design for the "Fat Finger" problem?', a: 'Touch targets on mobile devices must be a minimum of 44x44 CSS pixels (according to Apple/WCAG) to ensure users can accurately tap them without hitting adjacent interactive elements.' },
  { level: 'expert', q: 'What is a Design System vs a UI Library?', a: 'A UI Library is purely a collection of coded components. A Design System is a complete set of standards, documentation, design tokens, voice & tone guidelines, and the UI library, intended to manage design at scale.' },

  // UX/UI EXPERT MODERATION / RESEARCH (15)
  { level: 'expert', q: 'What is the "Paradox of Choice" in UX?', a: 'An observation that providing too many options can lead to anxiety and decision paralysis, eventually leading users to abandon the task entirely. Mitigation: Categorization, progressive disclosure, and smart defaults.' },
  { level: 'expert', q: 'Explain "Mental Models" and "Conceptual Models".', a: 'A mental model is what the user *thinks* they know about how a system works. A conceptual model is the actual design as implemented. UX friction occurs when these two models do not align.' },
  { level: 'expert', q: 'What is "Emotional Design" (Don Norman)?', a: 'Designing for three levels of processing: Visceral (automatic response to aesthetics), Behavioral (satisfaction with usability), and Reflective (conscious thought about brand and meaning).' },
  { level: 'expert', q: 'What are "Micro-interactions" and why do they matter?', a: 'Tiny functional movements (like a button ripple or a success checkmark animation) that provide instant feedback. They humanize the interface and prevent user uncertainty.' },
  { level: 'expert', q: 'Explain the "Peak-End Rule" in UX Research.', a: 'Users judge an experience largely based on how they felt at its peak (most intense point) and at its end, rather than the average of every moment of the experience.' },
  { level: 'expert', q: 'What is "Service Design" vs "Product Design"?', a: 'Product design focuses on a specific software artifact. Service design maps the entire end-to-end journey across all touchpoints (digital, physical, human) to improve the overall service quality.' },
  { level: 'expert', q: 'Compare Contextual Inquiry vs User Interviews.', a: 'User interviews are semi-structured conversations. Contextual Inquiry involves observing the user in their actual environment doing their actual work, uncovering behaviors that users might not mention in an interview.' },
  { level: 'expert', q: 'What is a "Card Sort" test?', a: 'A research method where users organize information into groups that make sense to them. Generative: users create their own categories. Closed: users sort into predefined categories. Used to design Information Architecture.' },
  { level: 'expert', q: 'Explain "Affordance" vs "Signifiers".', a: 'Affordance is the *possibility* of an action (a chair affords sitting). A signifier is the visual signal that tells the user the action is possible (a button\'s shadow is a signifier of its affordance to be clicked).' },
  { level: 'expert', q: 'What is "Design Debt"?', a: 'The accrued cost of poor design decisions (shortcuts, inconsistencies) that result in a more difficult user experience and slower development speed over time.' },
  { level: 'expert', q: 'What is "System Usability Scale" (SUS)?', a: 'A quick, reliable 10-item questionnaire used to measure the perceived usability of a system. It provides a score from 0-100 that can be benchmarked against industry averages.' },
  { level: 'expert', q: 'Explain "Atomic Design" methodology.', a: 'A system for building interfaces by Brad Frost: Atoms (labels, inputs) -> Molecules (search form) -> Organisms (header) -> Templates (page structure) -> Pages (real content).' },
  { level: 'expert', q: 'What is "Eye Tracking" and when should it be used?', a: 'A research tool that measures where users look on a screen. Used to identify "blind spots", verify visual hierarchy, and see if critical CTAs are actually being noticed.' },
  { level: 'expert', q: 'What are "User Journey Maps" vs "User Flows"?', a: 'A User Flow is a linear diagram of steps a user takes through the UI. A Journey Map is a high-level visualization of the user\'s emotions, motivations, and pain points across the entire experience.' },
  { level: 'expert', q: 'What is the "Doherty Threshold"?', a: 'The observation that productivity skyrockets when a computer and its users interact at a pace (< 400ms) that ensures neither has to wait on the other. It defines the UX requirement for "instant" feedback.' }
];

