export const sysDesignQA = [
  // SYSTEM DESIGN BEGINNER (10)
  { level: 'basic', q: 'What is System Design?', a: 'The process of defining the architecture, modules, interfaces, and data for a system to satisfy specified requirements. It\'s about making high-level architectural choices to scale.' },
  { level: 'basic', q: 'What is a Load Balancer?', a: 'A device or software (like Nginx or HAProxy) that acts as a reverse proxy and distributes network or application traffic across a number of servers to prevent single-point overload.' },
  { level: 'basic', q: 'Explain Horizontal vs Vertical Scaling.', a: 'Vertical scaling (Scaling Up) means upgrading a single server\'s hardware. Horizontal scaling (Scaling Out) means adding more independent servers to a pool to share the load.' },
  { level: 'basic', q: 'What is a CDN (Content Delivery Network)?', a: 'A geographically distributed network of proxy servers and their data centers. The goal is to cache static assets (like images, JS, CSS) closer to users to reduce latency drastically.' },
  { level: 'basic', q: 'What is database caching?', a: 'Storing frequently accessed data in a fast, in-memory store (like Redis or Memcached) to reduce the number of slow, heavy queries hitting the primary database.' },
  { level: 'basic', q: 'What does stateful vs stateless mean?', a: 'A stateless architecture means the server does not store any information about the client session (every request must contain all auth info, like JWTs). Stateful means the server remembers the client (like saving a session ID in memory).' },
  { level: 'basic', q: 'What is the purpose of a Reverse Proxy?', a: 'A server that sits in front of web servers and forwards client requests to them. Used for load balancing, SSL termination, and caching.' },
  { level: 'basic', q: 'Explain basically what a Microservice architecture is.', a: 'Breaking down a massive monolithic application into small, independent, specialized services that communicate over APIs. Each service can be developed, deployed, and scaled totally independently.' },
  { level: 'basic', q: 'What is DNS?', a: 'Domain Name System. The phonebook of the internet. It translates human-readable domain names (google.com) into computer-readable IP addresses.' },
  { level: 'basic', q: 'What is API Rate Limiting?', a: 'Restricting the number of requests a user or IP can make to an API within a specific time window to prevent abuse, scraping, or DDoS attacks.' },

  // SYSTEM DESIGN INTERMEDIATE / ADVANCED (10)
  { level: 'intermediate', q: 'Explain the CAP Theorem.', a: 'In a distributed data store, you can only mathematically guarantee two of three traits: Consistency (every read gets the latest write), Availability (every request gets a response), and Partition Tolerance (system works despite network drops). Because of network physics, you must choose CP or AP.' },
  { level: 'advanced', q: 'What is Database Sharding?', a: 'Horizontally partitioning a database. Instead of one massive DB, you split data across multiple databases using a shard key (e.g., users A-M on DB1, N-Z on DB2). It solves pure dataset size limits but makes cross-shard joins impossible.' },
  { level: 'intermediate', q: 'What is the "Thundering Herd" problem in caching?', a: 'When a popular cache key expires, thousands of concurrent requests miss the cache simultaneously and instantly slam the primary database, often crashing it. Solution: Use cache locks or add slight random jitter to expiration times.' },
  { level: 'advanced', q: 'Explain Eventual Consistency vs Strong Consistency.', a: 'Strong consistency guarantees that once a write occurs, all subsequent reads instantly reflect it (slow). Eventual consistency allows temporary staleness across replicated nodes, but guarantees they will ultimately synchronize (fast).' },
  { level: 'advanced', q: 'What is Long Polling vs WebSockets vs Server-Sent Events?', a: 'Long polling holds an HTTP connection open until the server has new data. WebSockets provide a true full-duplex, persistent TCP connection for two-way realtime data. Server-Sent Events (SSE) provide a persistent one-way connection from server to client.' },
  { level: 'expert', q: 'Explain Consistent Hashing and why it is used.', a: 'A hashing technique used in distributed systems (like Memcached clusters). Instead of modulo hashing which requires massive data reshuffling if a node is added/removed, consistent hashing places nodes on a circular hash ring, meaning adding/removing a node only disrupts its immediate neighbor.' },
  { level: 'advanced', q: 'What is a Message Queue?', a: 'An asynchronous service-to-service communication mechanism (like RabbitMQ or Kafka) used to decouple heavy processing. App servers push tasks onto the queue instantly, while worker servers pull tasks off the queue at their own pace without crashing.' },
  { level: 'intermediate', q: 'What is the difference between SQL and NoSQL?', a: 'SQL offers strict schemas, complex joins, and ACID compliance (scale vertically). NoSQL offers flexible schemas, sacrifices strong consistency for massive horizontal scalability, and is optimized for specific access patterns like key-value or document storage.' },
  { level: 'expert', q: 'What is the Two-Phase Commit (2PC) protocol?', a: 'A distributed algorithm that coordinates all processes participating in a distributed atomic transaction on whether to commit or abort (rollback) the transaction. It ensures ACID properties across multiple disparate databases.' },
  { level: 'expert', q: 'How would you design a URL shortener like bit.ly?', a: 'Requirements: High read-to-write ratio. Tech: Relational DB for strict ACID, or NoSQL for sheer scale. Algorithm: Base62 encoding of a unique auto-incrementing integer ID. Use Memcached heavily to cache the `shortURL -> longURL` mapping since reads outnumber writes 100:1.' }
];

export const uxUiQA = [
  // UX/UI BEGINNER (10)
  { level: 'basic', q: 'What is the difference between UX and UI?', a: 'UX (User Experience) is the analytical logic, psychology, and feel of the experience (wireframes, research, user journeys). UI (User Interface) is the visual skin, typography, colors, and layout (the aesthetic presentation).' },
  { level: 'basic', q: 'What is whitespace (negative space)?', a: 'The empty area separating different visual elements. It is crucial for preventing cognitive overload and effectively grouping related items together.' },
  { level: 'basic', q: 'What is progressive disclosure?', a: 'An interaction design technique that defers advanced or rarely used features to a secondary screen/dropdown, making applications easier to learn and less error-prone. (e.g., An "Advanced Settings" toggle).' },
  { level: 'basic', q: 'What is a Call to Action (CTA)?', a: 'A prominent button or link designed to prompt an immediate response or encourage an immediate sale (e.g., "Sign Up Now" or "Buy It").' },
  { level: 'basic', q: 'What is the 60-30-10 color rule?', a: 'A classic design principle for creating a balanced color palette. 60% is your dominant hue (usually background), 30% is your secondary color, and 10% is your accent color (CTAs and highlights).' },
  { level: 'basic', q: 'What are wireframes vs mockups vs prototypes?', a: 'Wireframes are low-fidelity structural blueprints (gray boxes). Mockups are high-fidelity static visual designs (colors and fonts). Prototypes are interactive models simulating the final flow.' },
  { level: 'basic', q: 'Why is Typography important in UI?', a: 'It establishes visual hierarchy, guides eye tracking, heavily impacts readability, and sets the entire emotional tone and brand identity of an application.' },
  { level: 'basic', q: 'What is Affordance in design?', a: 'A physical characteristic of an object or interface that visually hints at how it should be used. For example, a 3D shadow on a button affords clicking. A slider affords dragging.' },
  { level: 'basic', q: 'What is Mobile-First Design?', a: 'Designing the UI and UX for the smallest screen (mobile) first, focusing purely on core features, and progressively enhancing the layout for larger tablet and desktop screens.' },
  { level: 'basic', q: 'What does accessibility mean in UI design?', a: 'Ensuring your design is usable by people with disabilities. This means maintaining high color contrast, ensuring keyboard navigability, and providing screen-reader labels.' },

  // UX/UI INTERMEDIATE/ADVANCED (10)
  { level: 'intermediate', q: 'Explain Fitts\'s Law.', a: 'The time required to move to a target is a function of the distance to the target and the size of the target. Therefore, primary actions should be large and close to the user\'s natural starting position.' },
  { level: 'intermediate', q: 'Explain Hick\'s Law.', a: 'The time it takes to make a decision increases with the number and complexity of choices. In UX, this means you should minimize the number of options (e.g. navigation links) presented at once to prevent paralysis.' },
  { level: 'intermediate', q: 'What is the Gestalt Principle of Proximity?', a: 'Items physically close to each other are perceived as being grouped or related to one another. It is the strongest way to establish relationships without drawing literal bounding boxes.' },
  { level: 'advanced', q: 'What is the Aesthetic-Usability Effect?', a: 'A psychological phenomenon where users perceive more aesthetically pleasing designs to be more intuitive and easier to use than less pleasing designs, even if the actual usability is identical.' },
  { level: 'advanced', q: 'Describe Skeleton Screens vs Spinners.', a: 'Skeleton screens display a blank version of a page into which information is gradually loaded, reducing the user\'s *perceived* wait time. Spinners just show a loading wheel and increase frustration for long loads.' },
  { level: 'advanced', q: 'What are Dark Patterns?', a: 'UI and UX design choices specifically engineered to trick users into doing things they did not intend to do, like sneaking items into a cart or making the "Cancel Subscription" button invisible.' },
  { level: 'expert', q: 'What is Cognitive Load in UX?', a: 'The total amount of mental effort being used in the working memory. Extraneous cognitive load generated by cluttered UI, unclear labels, and disruptive pop-ups severely degrades user success rates.' },
  { level: 'advanced', q: 'Explain Heuristic Evaluation.', a: 'A usability engineering method where evaluators examine the UI and judge its compliance with recognized usability principles (the "heuristics"), such as Nielsen\'s 10 Usability Heuristics.' },
  { level: 'expert', q: 'How do you design for the "Fat Finger" problem?', a: 'Touch targets on mobile devices must be a minimum of 44x44 CSS pixels (according to Apple/WCAG) to ensure users can accurately tap them without hitting adjacent interactive elements.' },
  { level: 'expert', q: 'What is a Design System vs a UI Library?', a: 'A UI Library is purely a collection of coded components. A Design System is a complete set of standards, documentation, design tokens, voice & tone guidelines, and the UI library, intended to manage design at scale.' }
];
