export const nextQA = [
  // BEGINNER (15)
  { level: 'basic', q: 'What is Next.js?', a: 'A React framework created by Vercel that provides building blocks to create fast, full-stack web applications, offering features like SSR, SSG, routing, and API endpoints out of the box.' },
  { level: 'basic', q: 'What is the main difference between React and Next.js?', a: 'React is a library for building UIs, usually resulting in Client-Side Rendered (CSR) Single Page Applications. Next.js is a framework built ON TOP of React that handles routing, server-side rendering, and tooling.' },
  { level: 'basic', q: 'What is SSR (Server-Side Rendering)?', a: 'Rendering HTML on the server for each distinct request. The client receives a fully populated HTML document, improving SEO and initial page load speed.' },
  { level: 'basic', q: 'What is SSG (Static Site Generation)?', a: 'Rendering HTML on the server ONCE at build time. The static HTML is then cached on a CDN and served instantly to all users.' },
  { level: 'basic', q: 'What is the App Router in Next.js 13+?', a: 'A new file-system based router built on top of React Server Components, replacing the old `pages` directory. It uses folders to define routes and `page.tsx` for UI.' },
  { level: 'basic', q: 'What is a Server Component vs a Client Component?', a: 'Server Components run purely on the server and never ship their JS to the browser. Client Components (marked with `"use client"`) run on both server and client (hydration), allowing event listeners (onClick) and state (useState).' },
  { level: 'basic', q: 'How do you create a Client Component?', a: 'Add the `"use client"` directive at the very top of the file, before any imports. Note: This marks the component AND all its imported children as client-side.' },
  { level: 'basic', q: 'What is the <Image> component?', a: 'An optimized replacement for `<img>`. It automatically prevents Cumulative Layout Shift (CLS), lazy loads images, and optimizes sizes and formats (like WebP/AVIF) dynamically.' },
  { level: 'basic', q: 'What is the <Link> component?', a: 'An extension of the HTML `<a>` tag that enables client-side navigation between Next.js routes. It pre-fetches linked pages in the background for instant transitions.' },
  { level: 'basic', q: 'What is `next/font`?', a: 'A module that automatically optimizes fonts. It downloads them at build time and hosts them alongside your static assets, eliminating external network requests (like to Google Fonts) and preventing layout shift.' },
  { level: 'basic', q: 'What does a `layout.tsx` file do?', a: 'It provides shared UI for all routes within its directory and subdirectories. Crucially, it does not re-render or lose state when navigating between its children.' },
  { level: 'basic', q: 'What is an API Route (Route Handler)?', a: 'A way to build a backend API directly within Next.js. In the App Router, this is done by creating a `route.ts` file that exports HTTP methods like `GET`, `POST`, `PUT`, etc.' },
  { level: 'basic', q: 'How do you handle 404 pages in the App Router?', a: 'By creating a `not-found.tsx` file in a directory. It will automatically be rendered if the URL doesn\'t match a route, or if you explicitly call the `notFound()` function.' },
  { level: 'basic', q: 'What is the `public` directory used for?', a: 'Serving static assets like images, fonts, or `robots.txt` that can be mapped directly to the base URL (`/image.png`).' },
  { level: 'basic', q: 'How do you define dynamic routes?', a: 'By wrapping a folder name in square brackets, e.g., `[id]`. Inside that folder\'s `page.tsx`, you can access the dynamic value via `props.params.id`.' },

  // INTERMEDIATE & ADVANCED (30)
  { level: 'intermediate', q: 'What is ISR (Incremental Static Regeneration)?', a: 'A feature that allows you to update static pages AFTER you have built your site. You can generate static pages in the background without needing to rebuild the entire application.' },
  { level: 'intermediate', q: 'How do you use ISR in the App Router?', a: 'By exporting a route segment config: `export const revalidate = 60;` (revalidate every 60 seconds), or using the `next: { revalidate: 60 }` option in a `fetch()` call.' },
  { level: 'intermediate', q: 'What is On-Demand Revalidation?', a: 'Manually purging the cache for a specific page or tag. Instead of waiting for a timer (ISR), you call `revalidatePath("/blog")` or `revalidateTag("posts")` when your database updates.' },
  { level: 'intermediate', q: 'What is the difference between Parallel Routes and Intercepting Routes?', a: 'Parallel Routes (`@folder`) let you render multiple pages in the same layout simultaneously. Intercepting Routes (`(.)folder`) let you hijack navigation to render a route within the current layout (like a modal) instead of doing a hard redirect.' },
  { level: 'intermediate', q: 'Where should you place data fetching in the App Router?', a: 'Ideally in Server Components at the highest level possible. Use `await fetch()` directly in the async component body, and pass data down to Client Components via props.' },
  { level: 'intermediate', q: 'How does Next.js handle data deduplication?', a: 'If you call `fetch("url")` multiple times across different components during the same server render pass, Next.js intercepts it and only makes ONE actual network request.' },
  { level: 'intermediate', q: 'Can you pass functions from a Server Component to a Client Component?', a: 'No, functions are not serializable. Server Components can only pass JSON-serializable data (strings, numbers, simple objects/arrays) to Client Components. The exception is Server Actions.' },
  { level: 'advanced', q: 'What is a Server Action?', a: 'An asynchronous function marked with `"use server"` that can be passed directly to Client Components (like a form action or button click). Next.js automatically creates a hidden API endpoint for it.' },
  { level: 'advanced', q: 'How do you handle loading states for fetching data?', a: 'Create a `loading.tsx` file next to your page. Next.js instantly renders this fallback UI while the page\'s async Server Component is awaiting data resolution.' },
  { level: 'advanced', q: 'What is Next.js Middleware?', a: 'Code that executes on the Edge before a request completes. It allows you to rewrite, redirect, add headers, or set cookies before the router even initializes.' },
  { level: 'advanced', q: 'What are the limitations of the Edge Runtime?', a: 'It does not support native Node.js APIs (like `fs`, `child_process`, or `crypto` via node) and requires APIs like databases to be accessible over HTTP/Edge-compatible drivers.' },
  { level: 'advanced', q: 'Explain the difference between Node.js runtime and Edge runtime in Next.js.', a: 'Node.js runtime gives you access to the full Node ecosystem but suffers from cold starts. Edge runtime runs on Vercel\'s CDN globally, offering zero cold starts and instant execution, but restricted API access.' },
  { level: 'advanced', q: 'How do you generate dynamic metadata for SEO?', a: 'Export an async `generateMetadata({ params })` function from your `page.tsx` or `layout.tsx`. You can fetch data there to return specific titles and Open Graph tags.' },
  { level: 'advanced', q: 'What happens if `generateMetadata` and default `page.tsx` both fetch the same data API?', a: 'Because Next.js automatically dedupes `fetch` requests, the database or API is only hit once, making it completely safe and performant to request the same data in both places.' },
  { level: 'advanced', q: 'How do you handle environment variables in Next.js?', a: 'Variables in `.env` are private by default. To expose a variable to the browser (Client Components), you must prefix it with `NEXT_PUBLIC_`.' },
  { level: 'advanced', q: 'What is Turbopack?', a: 'An incremental bundler optimized for Next.js, written in Rust. It serves as an ultra-fast replacement for Webpack during development (`next dev --turbo`).' },
  { level: 'advanced', q: 'What is the significance of the "standalone" output mode?', a: 'Configured in `next.config.js`. It creates a folder containing strictly the files and `node_modules` required to run production. Highly recommended for optimizing Docker deployments (cutting gigabytes down to megabytes).' },
  { level: 'advanced', q: 'How does Partial Prerendering (PPR) work in Next.js?', a: 'An experimental feature (v14/15) where the compiler wraps dynamic parts of your page (like a shopping cart) in Suspense. At build time, it static-generates the static shell, and at runtime, it streams in the dynamic hole.' },
  { level: 'expert', q: 'What are the 4 layers of caching in the Next.js App Router?', a: '1. Request Memoization (dedupes fetches during render). 2. Data Cache (persists fetch data across requests). 3. Full Route Cache (persists static HTML/RSC payloads on the server). 4. Router Cache (persists RSC payloads in the browser memory for instant backward/forward navigation).' },
  { level: 'expert', q: 'How do you force a route to be completely dynamic (skip all caching)?', a: 'Export `export const dynamic = "force-dynamic";` from the segment, or use dynamic functions like `cookies()`, `headers()`, or URL `searchParams`.' },
  { level: 'expert', q: 'How does Streaming work in Next.js App Router?', a: 'Instead of waiting for all data to load on the server before sending HTML, Next.js immediately sends the static HTML parts. As async Server Components finish fetching, Next.js streams the HTML chunks over the same HTTP connection.' },
  { level: 'advanced', q: 'How do you implement i18n (Internationalization) in the App Router?', a: 'Typically by using incredibly dynamic routes like `app/[lang]/page.tsx` and using Middleware to detect the user\'s accept-language header, automatically redirecting them to the correct `/[lang]` path.' },
  { level: 'advanced', q: 'Why shouldn\'t you use React Context if you can avoid it in App Router?', a: 'Because Context boundaries force all components "under" them to become Client Components (if they consume it). This defeats the purpose of Server Components. Pass props, use Server Components, or push Context as deep into the tree as possible.' },
  { level: 'expert', q: 'What is the "poisoning" rule in Server Components?', a: 'If you import a Client Component into a Server Component, that\'s fine. But if you import a Server Component INTO a Client Component directly, it becomes a Client Component. You must pass Server Components as `children` props to bypass this.' },
  { level: 'expert', q: 'What is the `server-only` package?', a: 'A utility package you can import. If a developer accidentally imports that file into a File containing database passwords or secret keys, it throws an immediate build error.' },

  // --- NEW ADDITIONS (40+ ADDITIONAL ITEMS) ---
  // AUTHENTICATION & SECURITY
  { level: 'intermediate', q: 'What is Auth.js (NextAuth.js v5)?', a: 'The modern authentication solution for Next.js. It supports OAuth providers, email/password, and integrates directly with the App Router via Server Actions and Middleware.' },
  { level: 'advanced', q: 'Explain JWT vs. Session strategy in NextAuth.', a: 'JWT (JSON Web Token) is stateless and stored in a cookie. Sessions are stored in a database. JWT is usually faster and can be used on the Edge, while Sessions allow for immediate invalidation.' },
  { level: 'expert', q: 'How do you protect specific API routes using Middleware?', a: 'By checking for a valid session token in the request cookies inside `middleware.ts` and redirecting the user to `/login` if it is missing before the request even reaches the Route Handler.' },
  { level: 'advanced', q: 'What is the danger of using `process.env` in Client Components?', a: 'It will be undefined in the browser unless you prefix the variable with `NEXT_PUBLIC_`. However, sensitive keys (like DB passwords) should NEVER be prefixed, as they would be exposed to the user.' },
  { level: 'expert', q: 'How do you prevent CSRF in Next.js Server Actions?', a: 'Next.js has built-in CSRF protection for Server Actions. It compares the `Origin` header with the `Host` header to ensure the request is coming from your own domain.' },

  // DATABASES & DATA LIFECYCLE
  { level: 'intermediate', q: 'What is Prisma and why use it with Next.js?', a: 'An ORM (Object-Relational Mapper) that provides a typesafe database client. It makes querying databases like PostgreSQL or MySQL easier and prevents runtime type errors.' },
  { level: 'advanced', q: 'What is Drizzle ORM and how does it compare to Prisma?', a: 'A "lean" ORM that is zero-runtime and fully typesafe. Unlike Prisma, it doesn\'t require a separate engine binary, making it much more compatible with the Edge Runtime.' },
  { level: 'expert', q: 'How do you handle database connection pooling in Serverless environments?', a: 'By using a connection pooler like PgBouncer or using an HTTP-based database driver (like Upstash for Redis or Neon for Postgres) to avoid exhausting connection limits during high traffic.' },
  { level: 'advanced', q: 'What is the purpose of `useFormState` in Next.js 14/15?', a: 'It\'s used to manage the state returned from a Server Action (e.g., validation errors or success messages), allowing the UI to react to the server\'s response without manual state management.' },

  // ARCHITECTURE & ROUTING (DEEP DIVE)
  { level: 'advanced', q: 'What are Parallel Routes and when to use them?', a: 'Represented by `@folder`. They allow you to render multiple independent pages at the same URL (e.g., a Dashboard with a Sidebar and a Main view that can each have their own loading states).' },
  { level: 'advanced', q: 'Explain Intercepting Routes (modal pattern).', a: 'Represented by `(.)folder`. This allows you to "intercept" a navigation to a specific route and render it as a modal over the current context, while still allowing a refresh/share to show the target route as a standalone page.' },
  { level: 'expert', q: 'What is "Route Segment Config" and list 3 options.', a: 'Configuration exported from a page/layout to control its behavior. Options: `dynamic` ("auto", "force-dynamic"), `revalidate` (seconds), `runtime` ("nodejs", "edge").' },
  { level: 'advanced', q: 'What is the `unstable_cache` API?', a: 'A function that allows you to cache data-fetching results that AREN\'T using the standard `fetch()` API (e.g., direct DB queries via an ORM).' },
  { level: 'expert', q: 'Explain "Static Metadata" vs "dynamic metadata" hoisting.', a: 'Static is defined as a constant `export const metadata`. Dynamic uses `export async function generateMetadata()`. Both are hoisted to the head, but dynamic allows fetching data for page-specific titles.' },

  // OPTIMIZATION & PERFORMANCE
  { level: 'intermediate', q: 'What is the "priority" prop in Next.js Image?', a: 'It tells Next.js to preload the image and treat it as a high-priority asset, which is crucial for the LCP (Largest Contentful Paint) image.' },
  { level: 'advanced', q: 'How does Next.js handle Third-Party Scripts?', a: 'Via the `<Script>` component. It allows strategies like `afterInteractive` (default), `beforeInteractive` (early load), and `worker` (offload to web worker).' },
  { level: 'expert', q: 'What is Partial Prerendering (PPR)?', a: 'A build-time optimization that static-generates a page\'s "shell" and leaves "holes" for dynamic content that are streamed in at runtime using Suspense boundaries.' },
  { level: 'advanced', q: 'Explain the difference between `revalidatePath` and `revalidateTag`.', a: '`revalidatePath` purges the entire cache for a specific URL. `revalidateTag` purges all cached requests that were tagged with a specific string, which is more surgical and efficient.' },
  { level: 'expert', q: 'How do you optimize an app for the Edge Runtime?', a: 'Avoid Node-specific APIs, use Edge-compatible database drivers, and keep bundle sizes small since the Edge runtime has strict memory and CPU limits.' },

  // ECOSYSTEM & DEPLOYMENT
  { level: 'intermediate', q: 'What is the Vercel Data Cache?', a: 'An global cache that persists the result of `fetch` requests across multiple server executions and even redeploys, unless manually invalidated.' },
  { level: 'advanced', q: 'How do you deploy Next.js to a VPS (non-Vercel)?', a: 'By building the app with `output: "standalone"` and running the resulting `server.js` file using Node.js, usually managed by PM2 or inside a Docker container.' },
  { level: 'expert', q: 'What is "Request Memoization" vs "Data Cache"?', a: 'Memoization only lasts for ONE server request (preventing duplicate fetches). Data Cache persists ACROSS requests on the server storage indefinitely until revalidated.' },
  { level: 'intermediate', q: 'What is the purpose of the `.next` folder?', a: 'It is the build output directory containing compiled JS, cached static pages, RSC payloads, and configuration files used by the Next.js server.' },
  { level: 'advanced', q: 'How do you handle redirects in the App Router?', a: 'Using the `redirect()` function for server-side redirects, or the `redirects` config in `next.config.js` for permanent path mapping.' }
];
